### ISSUE TITLE
Blog: sidebar ZF sticky overlaps on top nav when scrolled

### ISSUE THREAD

**Issue by rr1000** [daticahealth/seldon-middleman#90]
To reproduce:

1.) Go to https://datica.com/blog/announcing-future-cloud-compliance-management-system/

2.) Scroll

3.) "Subscribe to email updates" box breaks header

**Comment by rr1000** [comment]
Example:

<img width="1068" alt="screen shot 2018-10-03 at 11 14 08 am" src="https://user-images.githubusercontent.com/1596785/46430419-ba55a280-c6fd-11e8-8144-7a95e310b45b.png">

**Comment by allanwhite** [comment]
@rr1000 Thanks for filing the bug - I am aware of this one. Getting Foundation's sticky system to behave/config has been a pain. It's in my backlog on the project board.

**Comment by allanwhite** [comment]
![image](https://user-images.githubusercontent.com/887931/46452418-91123200-c750-11e8-8706-cae1574da582.png)
